### ISSUE TITLE
Fix broken asset pipeline on Heroku

### ISSUE THREAD

**Issue by gilomen2** [gilomen2/timefor#38]

**Comment by dogweather** [comment]
Ack, I can totally help with this. Can you give me the error message and/or a screenshot and link?

**Comment by gilomen2** [comment]
@dogweather i'm not actually getting errors, i just have to precompile everything before i push to heroku to get changes in my assets to be reflected. i think what's going on is that not all of my stylesheets are SASS, and in the ones that are, i may not be referencing image and asset paths correctly for the asset pipeline. i've come across this before in other apps and that has been the problem.
